In [1]:
from pyhive import hive
from tqdm import tqdm
import numpy as np
import os
import pandas as pd

In [2]:
hive_cnx = hive.Connection(
    host='hd02.pdmnu.com'
    , username='sweetbarrow'
    , database='mlens'
    , auth='NOSASL'
)
hive_cnx

In [3]:
ratings_genres = pd.read_sql('SELECT * FROM mlens.ratings_genres', hive_cnx)
ratings_genres

,ratings_genres.user_id,ratings_genres.action,ratings_genres.adventure,ratings_genres.animation,ratings_genres.children,ratings_genres.comedy,ratings_genres.crime,ratings_genres.documentary,ratings_genres.drama,ratings_genres.fantasy,ratings_genres.film_noir,ratings_genres.horror,ratings_genres.imax,ratings_genres.musical,ratings_genres.mystery,ratings_genres.romance,ratings_genres.sci_fi,ratings_genres.thriller,ratings_genres.war,ratings_genres.western
0,1,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
1,2,2,2,0,0,6,1,0,6,0,0,1,0,1,0,3,1,3,0,0
2,3,1,1,0,1,1,1,0,4,0,0,0,0,0,1,0,0,2,1,0
3,4,192,104,17,-4,27,88,4,137,39,3,22,6,-3,31,26,78,167,25,0
4,5,13,7,0,0,17,31,2,48,2,2,0,1,0,11,8,3,24,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283223,283224,37,33,2,7,43,30,1,99,12,6,13,0,14,16,31,28,44,20,11
283224,283225,-3,-2,0,0,0,4,0,-1,0,1,0,0,-1,1,-1,-1,-1,-1,1
283225,283226,-6,-3,0,-1,-3,-2,0,-3,0,0,-1,0,0,-1,-1,-2,-4,0,0
283226,283227,2,0,0,3,4,2,0,6,0,0,0,0,0,0,2,0,3,0,1
283227,283228,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6

In [4]:
ratings_genres.columns

Index(['ratings_genres.user_id', 'ratings_genres.action',
       'ratings_genres.adventure', 'ratings_genres.animation',
       'ratings_genres.children', 'ratings_genres.comedy',
       'ratings_genres.crime', 'ratings_genres.documentary',
       'ratings_genres.drama', 'ratings_genres.fantasy',
       'ratings_genres.film_noir', 'ratings_genres.horror',
       'ratings_genres.imax', 'ratings_genres.musical',
       'ratings_genres.mystery', 'ratings_genres.romance',
       'ratings_genres.sci_fi', 'ratings_genres.thriller',
       'ratings_genres.war', 'ratings_genres.western'],
      dtype='object')

In [5]:
new_columns = {
    'ratings_genres.user_id': 'user_id'
    , 'ratings_genres.action': 'action'
    , 'ratings_genres.adventure': 'adventure'
    , 'ratings_genres.animation': 'animation'
    , 'ratings_genres.children': 'children'
    , 'ratings_genres.comedy': 'comedy'
    , 'ratings_genres.crime': 'crime'
    , 'ratings_genres.documentary': 'documentary'
    , 'ratings_genres.drama': 'drama'
    , 'ratings_genres.fantasy': 'fantasy'
    , 'ratings_genres.film_noir': 'film_noir'
    , 'ratings_genres.horror': 'horror'
    , 'ratings_genres.imax': 'imax'
    , 'ratings_genres.musical': 'musical'
    , 'ratings_genres.mystery': 'mystery'
    , 'ratings_genres.romance': 'romance'
    , 'ratings_genres.sci_fi': 'sci_fi'
    , 'ratings_genres.thriller': 'thriller'
    , 'ratings_genres.war': 'war'
    , 'ratings_genres.western': 'western'
}
new_columns

{'ratings_genres.user_id': 'user_id',
 'ratings_genres.action': 'action',
 'ratings_genres.adventure': 'adventure',
 'ratings_genres.animation': 'animation',
 'ratings_genres.children': 'children',
 'ratings_genres.comedy': 'comedy',
 'ratings_genres.crime': 'crime',
 'ratings_genres.documentary': 'documentary',
 'ratings_genres.drama': 'drama',
 'ratings_genres.fantasy': 'fantasy',
 'ratings_genres.film_noir': 'film_noir',
 'ratings_genres.horror': 'horror',
 'ratings_genres.imax': 'imax',
 'ratings_genres.musical': 'musical',
 'ratings_genres.mystery': 'mystery',
 'ratings_genres.romance': 'romance',
 'ratings_genres.sci_fi': 'sci_fi',
 'ratings_genres.thriller': 'thriller',
 'ratings_genres.war': 'war',
 'ratings_genres.western': 'western'}

In [6]:
ratings_genres.rename(columns=new_columns, inplace=True)
ratings_genres

,user_id,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
0,1,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
1,2,2,2,0,0,6,1,0,6,0,0,1,0,1,0,3,1,3,0,0
2,3,1,1,0,1,1,1,0,4,0,0,0,0,0,1,0,0,2,1,0
3,4,192,104,17,-4,27,88,4,137,39,3,22,6,-3,31,26,78,167,25,0
4,5,13,7,0,0,17,31,2,48,2,2,0,1,0,11,8,3,24,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283223,283224,37,33,2,7,43,30,1,99,12,6,13,0,14,16,31,28,44,20,11
283224,283225,-3,-2,0,0,0,4,0,-1,0,1,0,0,-1,1,-1,-1,-1,-1,1
283225,283226,-6,-3,0,-1,-3,-2,0,-3,0,0,-1,0,0,-1,-1,-2,-4,0,0
283226,283227,2,0,0,3,4,2,0,6,0,0,0,0,0,0,2,0,3,0,1
283227,283228,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6

In [7]:
ratings_rescaled = pd.read_sql('SELECT * FROM mlens.ratings_rescaled', hive_cnx)
ratings_rescaled

,ratings_rescaled.user_id,ratings_rescaled.movie_id,ratings_rescaled.rating_rescaled
0,1,307,1
1,1,481,1
2,1,1091,-1
3,1,1257,1
4,1,1449,1
...,...,...,...
27753439,283228,8542,1
27753440,283228,8712,1
27753441,283228,34405,1
27753442,283228,44761,1
27753443,283228,54286,1

In [8]:
ratings_rescaled.rename(
    columns={
        'ratings_rescaled.user_id': 'user_id'
        , 'ratings_rescaled.movie_id': 'movie_id'
        , 'ratings_rescaled.rating_rescaled': 'rating'
    }
    , inplace=True
)
ratings_rescaled

          user_id  movie_id  rating
0               1       307       1
1               1       481       1
2               1      1091      -1
3               1      1257       1
4               1      1449       1
...           ...       ...     ...
27753439   283228      8542       1
27753440   283228      8712       1
27753441   283228     34405       1
27753442   283228     44761       1
27753443   283228     54286       1

[27753444 rows x 3 columns]

In [9]:
ratings_merged = ratings_rescaled.merge(ratings_genres, how='left', left_on='user_id', right_on='user_id'
                                      , left_index=False, right_index=False
                                     , suffixes=('_resc', '_genres'))
ratings_merged

,user_id,movie_id,rating,action,adventure,animation,children,comedy,crime,documentary,...,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
0,1,307,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
1,1,481,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
2,1,1091,-1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
3,1,1257,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
4,1,1449,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27753439,283228,8542,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753440,283228,8712,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753441,283228,34405,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753442,283228,44761,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753443,283228,54286,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6

In [10]:
ratings_refined = ratings_merged.drop(ratings_merged[ratings_merged['rating'] < 1].index, axis=0, inplace=True)
ratings_refined

,user_id,movie_id,rating,action,adventure,animation,children,comedy,crime,documentary,...,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
0,1,307,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
1,1,481,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
3,1,1257,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
4,1,1449,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
7,1,2134,1,0,-1,0,0,4,0,0,...,0,-2,0,0,0,2,-2,-2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27753439,283228,8542,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753440,283228,8712,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753441,283228,34405,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753442,283228,44761,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6
27753443,283228,54286,1,25,18,4,5,43,24,0,...,9,6,0,4,23,31,10,34,8,6

In [11]:
ratings_refined.drop(['user_id', 'rating'], axis=1, inplace=True)
ratings_refined

,movie_id,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
0,307,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
1,481,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
3,1257,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
4,1449,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
7,2134,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27753439,8542,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6
27753440,8712,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6
27753441,34405,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6
27753442,44761,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6
27753443,54286,25,18,4,5,43,24,0,43,8,9,6,0,4,23,31,10,34,8,6

In [12]:
movies = pd.read_sql('SELECT * FROM mlens.movies', hive_cnx)
movies

,movies.movieid,movies.title,movies.genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
58093,175409,Nicostratos the Pelican (2011),Comedy|Drama
58094,175411,Surviving Sid (2008),Animation
58095,175413,Likes or Dislikes (2014),Comedy|Romance
58096,175415,But What If This Is Love? (1961),Drama|Romance
58097,175417,Puzzled Love (2010),Comedy|Romance

In [13]:
movies.drop('movies.title', axis=1, inplace=True)
movies.rename(columns={'movies.movieid': 'movie_id', 'movies.genres': 'genres'}, inplace=True)
movies

       movie_id                                       genres
0             1  Adventure|Animation|Children|Comedy|Fantasy
1             2                   Adventure|Children|Fantasy
2             3                               Comedy|Romance
3             4                         Comedy|Drama|Romance
4             5                                       Comedy
...         ...                                          ...
58093    175409                                 Comedy|Drama
58094    175411                                    Animation
58095    175413                               Comedy|Romance
58096    175415                                Drama|Romance
58097    175417                               Comedy|Romance

[58098 rows x 2 columns]

In [14]:
genres_splitted = movies['genres'].str.split('|')
genres_splitted

0        [Adventure, Animation, Children, Comedy, Fantasy]
1                           [Adventure, Children, Fantasy]
2                                        [Comedy, Romance]
3                                 [Comedy, Drama, Romance]
4                                                 [Comedy]
                               ...
58093                                      [Comedy, Drama]
58094                                          [Animation]
58095                                    [Comedy, Romance]
58096                                     [Drama, Romance]
58097                                    [Comedy, Romance]
Name: genres, Length: 58098, dtype: object

In [15]:
movies = movies.merge(genres_splitted, left_index=True, right_index=True)
movies

,movie_id,genres_x,genres_y
0,1,Adventure|Animation|Children|Comedy|Fantasy,"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Adventure|Children|Fantasy,"[Adventure, Children, Fantasy]"
2,3,Comedy|Romance,"[Comedy, Romance]"
3,4,Comedy|Drama|Romance,"[Comedy, Drama, Romance]"
4,5,Comedy,[Comedy]
...,...,...,...
58093,175409,Comedy|Drama,"[Comedy, Drama]"
58094,175411,Animation,[Animation]
58095,175413,Comedy|Romance,"[Comedy, Romance]"
58096,175415,Drama|Romance,"[Drama, Romance]"
58097,175417,Comedy|Romance,"[Comedy, Romance]"

In [16]:
genres = pd.read_sql('SELECT * FROM mlens.genres', hive_cnx)
genres

    genres.genre_id genres.genre_name
0                 0              NULL
1                 1            Action
2                 2         Adventure
3                 3         Animation
4                 4          Children
5                 5            Comedy
6                 6             Crime
7                 7       Documentary
8                 8             Drama
9                 9           Fantasy
10               10         Film-Noir
11               11            Horror
12               12              IMAX
13               13           Musical
14               14           Mystery
15               15           Romance
16               16            Sci-Fi
17               17          Thriller
18               18               War
19               19           Western

In [17]:
genres_dict = genres.to_dict(orient='records')
genres_dict

[{'genres.genre_id': 0, 'genres.genre_name': 'NULL'},
 {'genres.genre_id': 1, 'genres.genre_name': 'Action'},
 {'genres.genre_id': 2, 'genres.genre_name': 'Adventure'},
 {'genres.genre_id': 3, 'genres.genre_name': 'Animation'},
 {'genres.genre_id': 4, 'genres.genre_name': 'Children'},
 {'genres.genre_id': 5, 'genres.genre_name': 'Comedy'},
 {'genres.genre_id': 6, 'genres.genre_name': 'Crime'},
 {'genres.genre_id': 7, 'genres.genre_name': 'Documentary'},
 {'genres.genre_id': 8, 'genres.genre_name': 'Drama'},
 {'genres.genre_id': 9, 'genres.genre_name': 'Fantasy'},
 {'genres.genre_id': 10, 'genres.genre_name': 'Film-Noir'},
 {'genres.genre_id': 11, 'genres.genre_name': 'Horror'},
 {'genres.genre_id': 12, 'genres.genre_name': 'IMAX'},
 {'genres.genre_id': 13, 'genres.genre_name': 'Musical'},
 {'genres.genre_id': 14, 'genres.genre_name': 'Mystery'},
 {'genres.genre_id': 15, 'genres.genre_name': 'Romance'},
 {'genres.genre_id': 16, 'genres.genre_name': 'Sci-Fi'},
 {'genres.genre_id': 17, 'genres.genre_name': 'Thriller'},
 {'genres.genre_id': 18, 'genres.genre_name': 'War'},
 {'genres.genre_id': 19, 'genres.genre_name': 'Western'}]

In [18]:
genres_dict_new = {}

In [19]:
for _ in genres_dict:
    id_value = _['genres.genre_id']
    genre_value = _['genres.genre_name']
    genres_dict_new[genre_value] = id_value
genres_dict_new['(no genres listed)'] = 0
genres_dict_new

{'NULL': 0,
 'Action': 1,
 'Adventure': 2,
 'Animation': 3,
 'Children': 4,
 'Comedy': 5,
 'Crime': 6,
 'Documentary': 7,
 'Drama': 8,
 'Fantasy': 9,
 'Film-Noir': 10,
 'Horror': 11,
 'IMAX': 12,
 'Musical': 13,
 'Mystery': 14,
 'Romance': 15,
 'Sci-Fi': 16,
 'Thriller': 17,
 'War': 18,
 'Western': 19,
 '(no genres listed)': 0}

In [20]:
movies.head()

,movie_id,genres_x,genres_y
0,1,Adventure|Animation|Children|Comedy|Fantasy,"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Adventure|Children|Fantasy,"[Adventure, Children, Fantasy]"
2,3,Comedy|Romance,"[Comedy, Romance]"
3,4,Comedy|Drama|Romance,"[Comedy, Drama, Romance]"
4,5,Comedy,[Comedy]

In [21]:
from tqdm import trange
for index in trange(len(movies)):
    genres_list = []
    genres_data = movies.loc[index, 'genres_y']
    for genre in genres_data:
        list_index = genres_data.index(genre)
        genres_data[list_index] = genres_dict_new[genre]
    genres_list = np.array(genres_list)
    movies.at[index, 'genres_y'] = genres_list
movies

100%|█████████████████████████████████████████████████████████████████████████| 58098/58098 [00:00<00:00, 76923.92it/s]

       movie_id                                     genres_x genres_y
0             1  Adventure|Animation|Children|Comedy|Fantasy       []
1             2                   Adventure|Children|Fantasy       []
2             3                               Comedy|Romance       []
3             4                         Comedy|Drama|Romance       []
4             5                                       Comedy       []
...         ...                                          ...      ...
58093    175409                                 Comedy|Drama       []
58094    175411                                    Animation       []
58095    175413                               Comedy|Romance       []
58096    175415                                Drama|Romance       []
58097    175417                               Comedy|Romance       []

[58098 rows x 3 columns]

In [26]:
movies.drop(['genres_x','genres_y'], inplace=True, axis=1)
# movies.rename(columns={'genres_y': 'genres'}, inplace=True)
movies

       movie_id           genres
0             1  [2, 3, 4, 5, 9]
1             2        [2, 4, 9]
2             3          [5, 15]
3             4       [5, 8, 15]
4             5              [5]
...         ...              ...
58093    175409           [5, 8]
58094    175411              [3]
58095    175413          [5, 15]
58096    175415          [8, 15]
58097    175417          [5, 15]

[58098 rows x 2 columns]

In [73]:
ratings_new = ratings_refined.merge(movies, left_on='movie_id', right_on='movie_id')
ratings_new

NameError: name 'ratings_refined' is not defined

In [28]:
ratings_new.drop('movie_id', axis=1, inplace=True)
ratings_new

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western,genres
0,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1,[8]
1,0,3,1,1,6,7,0,11,0,0,1,1,1,3,5,1,8,2,1,[8]
2,-30,-42,-11,-40,-107,10,5,63,-14,1,-11,-5,-12,29,-22,9,-1,12,7,[8]
3,24,25,24,8,21,28,2,84,29,3,2,3,5,21,17,23,29,13,1,[8]
4,5,-1,2,-1,-4,10,0,13,1,1,4,0,-1,4,0,6,14,0,1,[8]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17243750,155,180,151,120,598,128,97,772,108,17,22,35,140,68,326,116,139,48,28,"[5, 13, 15]"
17243751,155,180,151,120,598,128,97,772,108,17,22,35,140,68,326,116,139,48,28,[7]
17243752,155,180,151,120,598,128,97,772,108,17,22,35,140,68,326,116,139,48,28,[0]
17243753,155,180,151,120,598,128,97,772,108,17,22,35,140,68,326,116,139,48,28,[7]
17243754,155,180,151,120,598,128,97,772,108,17,22,35,140,68,326,116,139,48,28,[5]

In [24]:
y_ = y.genres.tolist()

In [25]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
multi_labeling = preprocessing.MultiLabelBinarizer()
y_label = multi_labeling.fit_transform(y_)

In [73]:
y_label

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1]])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x.head()

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
0,0,-1,0,0,4,0,0,5,1,0,-2,0,0,0,2,-2,-2,0,1
1,0,3,1,1,6,7,0,11,0,0,1,1,1,3,5,1,8,2,1
2,-30,-42,-11,-40,-107,10,5,63,-14,1,-11,-5,-12,29,-22,9,-1,12,7
3,24,25,24,8,21,28,2,84,29,3,2,3,5,21,17,23,29,13,1
4,5,-1,2,-1,-4,10,0,13,1,1,4,0,-1,4,0,6,14,0,1

In [29]:
y_label

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1]])

In [74]:
x_train, x_test, y_train, y_test = train_test_split(x, y_label, random_state=0)

In [63]:
x_test

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film_noir,horror,imax,musical,mystery,romance,sci_fi,thriller,war,western
194257,15,12,2,3,12,3,0,13,4,3,-1,0,4,6,6,3,3,7,5
396319,4,4,3,2,29,13,1,65,5,2,2,1,11,9,30,9,21,6,0
138738,4,3,0,1,2,0,0,6,1,0,1,0,0,0,3,2,3,1,0
66570,0,2,0,0,16,3,0,25,2,0,1,0,-1,0,20,1,3,6,1
149424,19,15,0,1,14,1,0,7,12,0,4,7,0,4,4,11,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254749,159,141,75,60,225,73,7,260,85,3,37,52,27,53,125,110,127,25,6
186957,15,15,3,6,44,20,1,108,4,0,2,2,2,3,25,4,16,18,4
280743,45,27,2,2,21,39,0,66,5,4,7,9,0,18,11,26,49,7,5
223365,176,131,78,43,65,48,2,110,53,0,-1,40,4,22,39,111,87,10,0
276946,0,-1,1,1,3,4,0,6,0,0,0,0,0,0,4,0,1,1,0

In [31]:
import tensorflow as tf
import keras

Using TensorFlow backend.

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [33]:
model = Sequential()  # 신경망 순서 지정

In [49]:
from keras.layers import Dense, LSTM, Embedding, Dropout
from keras.optimizers import SGD

In [82]:
y_train.shape

(12932816, 14)

In [75]:
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=x_train.shape[1]))
model.add(Dense(60, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy',
              optimizer=sgd , metrics=['accuracy'])

In [40]:
# Dense: 한개의 층
# 1번째 층: 입력층, input_dim 파라미터는 입력층에만 존재한다.
# 중간층: 히든층 (여러 개, 옵션)
# 마지막 층: 출력층
model = Sequential()
model.add(Embedding(1000, 100))
model.add(LSTM(100, input_dim = 19,activation='relu'))
model.add(Dense(90, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(14, activation='sigmoid'))

C:\ProgramData\Anaconda3\envs\data-dl\lib\site-packages\ipykernel_launcher.py:7: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  import sys
C:\ProgramData\Anaconda3\envs\data-dl\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(100, activation="relu", input_shape=(None, 19))`
  import sys

In [41]:
model.compile(
    loss='binary_crossentropy'
    , optimizer='adam'
    , metrics=['accuracy']
)

In [77]:
model.fit(x_train, y_train, epochs=5, batch_size=5000)

Epoch 1/5
12932816/12932816 [==============================] - 20s 2us/step - loss: 0.4257 - accuracy: 0.8009
Epoch 2/5
12932816/12932816 [==============================] - 19s 2us/step - loss: 0.4200 - accuracy: 0.8024
Epoch 3/5
12932816/12932816 [==============================] - 20s 2us/step - loss: 0.4160 - accuracy: 0.8052
Epoch 4/5
12932816/12932816 [==============================] - 20s 2us/step - loss: 0.4131 - accuracy: 0.8059
Epoch 5/5
12932816/12932816 [==============================] - 20s 2us/step - loss: 0.4106 - accuracy: 0.8071

In [78]:
preds = model.predict(x_test)

In [79]:
preds[preds>=0.5] = 1
preds[preds<0.5] = 0

In [69]:
y_test.tolist()
y_pred = model.predict(x_test[:100])
label_ = y_test.tolist()

In [67]:
y_test.tolist()
y_pred = model.predict(x_test[:100]).flatten()
label_ = y_test.tolist()

In [80]:
label_

[[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
 [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],

In [83]:
y_pred

array([[8.8404894e-01, 8.8553756e-01, 7.7369565e-04, ..., 1.2240619e-01,
        9.9902511e-01, 9.9907744e-01],
       [8.6228657e-01, 8.6265028e-01, 9.2159142e-05, ..., 7.2463319e-02,
        9.9988174e-01, 9.9984396e-01],
       [9.4343555e-01, 9.4108355e-01, 9.2374638e-04, ..., 1.0294347e-01,
        9.9825352e-01, 9.9870527e-01],
       ...,
       [8.0248690e-01, 7.9999101e-01, 5.2778552e-05, ..., 6.0390487e-02,
        9.9990737e-01, 9.9990153e-01],
       [9.5602435e-01, 9.5260555e-01, 7.2394282e-04, ..., 1.6829257e-01,
        9.9937832e-01, 9.9940932e-01],
       [9.2024398e-01, 9.2657995e-01, 8.2058244e-04, ..., 6.6635311e-02,
        9.9916983e-01, 9.9893910e-01]], dtype=float32)

In [53]:
y_pred

array([9.0899545e-01, 9.1047454e-01, 1.0318526e-13, ..., 1.2282006e-01,
       1.0000000e+00, 1.0000000e+00], dtype=float32)

In [84]:
for i in range(0,100):
    label = label_[i]
    prediction = preds[i]
    print('실제 점수:',label ,'예상 점수:', prediction)

실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
실제 점수: [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 예상 점수: [1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]